### ISSUE TITLE
Saved Image not showing up in Design Center

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#359]
I saved an image of a door panel that showed up in the Default Folder in My Portfolio, but the image is broken in the Design Center. Not sure if this would have anything to do with it, but I'm wondering if it's an obsolete door panel style as I did not see it in the Door Configurator - could that cause the image to be broken in the Design Center but not on the site?
My Portfolio image:
![image](https://user-images.githubusercontent.com/78490468/165549741-a3728a4d-a463-4992-a371-5ec61ee75600.png)
Design Center (same image):
![image](https://user-images.githubusercontent.com/78490468/165549981-3858b2b3-fc22-47b1-92a8-19b03673a90a.png)
Image that I saved (on Signet page):
![image](https://user-images.githubusercontent.com/78490468/165550316-20c9f2a7-e7cf-4966-981d-eed7b6d731ed.png)

**Comment by ancaipen** [comment]
This bug has been fixed.  It appears that it was an html encoding error on my end because of the dash at the end of the original image name.  I was able to add this image to the vision board now.  

![image](https://user-images.githubusercontent.com/43222107/166157497-59f5b167-ddde-4881-b535-d367ae248ad9.png)

![image](https://user-images.githubusercontent.com/43222107/166157517-bfdf2e62-befe-4491-98e6-e6e675460087.png)

**Comment by PilotFish3447** [comment]
@ancaipen - this happened again on a different Signet door panel style (460):
![image](https://user-images.githubusercontent.com/78490468/166314561-bc94d1ba-f8c5-4562-9810-5500910266e4.png)
As well as panel style 400-4P and 419 -- Let me know if the fix is image specific. If so, then I probably need to test all the door panel styles. Let me know if I should do that.
![image](https://user-images.githubusercontent.com/78490468/166315073-dc9427c8-6039-4fc4-b14a-b2ebb67287af.png)
![image](https://user-images.githubusercontent.com/78490468/166315205-721a5fc1-2d47-4861-9c65-55746acb5784.png)

**Comment by PilotFish3447** [comment]
@ancaipen  Found 2 more door images not showing up when I save to Design Center: 440-4P and 002S -- All the rest look OK.
![image](https://user-images.githubusercontent.com/78490468/166981207-f516ed56-073f-4331-8881-223a188fdbee.png)
![image](https://user-images.githubusercontent.com/78490468/166982372-ed20add8-e53c-4ad5-a9fd-d7aaeacab9ef.png)

**Comment by PilotFish3447** [comment]
@ancaipen - When I saved these two specific images again, they do appear in my folder in the My Portfolio section, but they're still showing up as broken links on the Vision Board folder even though I added a ?sdfadswg to the end of the URL to clear the cache. So I don't know if this is a legit issue or if it's a caching issue: 
![image](https://user-images.githubusercontent.com/78490468/167219566-8338c5f8-046b-47ea-ae9e-c66ec19a6519.png)
![image](https://user-images.githubusercontent.com/78490468/167219765-5640358e-9124-407a-a703-f0483b2105f7.png)
![image](https://user-images.githubusercontent.com/78490468/167219824-6a76f9cb-bc65-46a0-a6f5-0ae1a67b0f1f.png)

**Comment by PilotFish3447** [comment]
@ancaipen They're the same images that weren't saving into my Design Center previously -- 440-4P and 002S -- twhen I re-tested, they did save successfully to the My Portfolio folder, but they still show up as broken links in My Design Center.  I cleared my cache multiple times and I wasn't on the site all weekend, so I'd think the cache wouldn't be an issue this many days later.  But those two images show up as broken links in the Vision Board repository and you can't move them onto the Vision Board - they just disappear.  But, when I refresh the page, they show up again the repository as broken links.  And, I decided to re-test them again, which I just did.  I deleted them from the My Portfolio folder, then re-saved them and they're still showing up as broken links next to the Vision Board.  It's just these two door panel images:  440-4P and 002S

**Comment by ancaipen** [comment]
@PilotFish3447 - Ok I found the issue and I think this is something that probably needs fixed with these images in elementor.  It looks like the path of these images is pointing to the old directory (proviasandbox).  It also looks like we have this mapping incorrect somewhere in WordPress because there is a wp-content folder that was last modfied in the site root instead of in the provia.com folder (where the rest of the images reside).  

![image](https://user-images.githubusercontent.com/43222107/167704191-6821e424-dd6a-4e36-b60c-82bdd97cc8fb.png)

With that said, I did make an exception for these images, but I think that long term it would be better to have these images in the folder: /provia.com/wp-content/uploads

![image](https://user-images.githubusercontent.com/43222107/167704616-a7cb6587-5fba-4880-ac03-be11a88be1af.png)

**Comment by PilotFish3447** [comment]
@ancaipen Do you want to discuss this issue with Sean on Thursday?  Perhaps we should keep it open so we can determine a permanent solution as you've outlined above.

**Comment by ancaipen** [comment]
@SeanIsAtWork @PilotFish3447 : I checked this morning and it looks like there is only a css file in there.  I would just double check to make sure that all file paths are pointing to the provia.com folder. Its possible that this was done in error and was fixed in the beginning of May?  Either way, I would like to remove this folder/file to avoid future confusion.  @SeanIsAtWork - take a look and let me know if it is ok to just delete this file.  Thanks!   

![image](https://user-images.githubusercontent.com/43222107/167853563-2a5e36a3-eee6-4c70-9d09-a45da3524620.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork : Its totally possible these images were uploaded before we moved servers and that is the issue with directory?  Either way, if you want to just move these files to the /uploads directory you will should be fine.  It will work either way with my code now, but it may make your life easier down the road.

**Comment by ancaipen** [comment]
@SeanIsAtWork : I'm closing this issue, I made adjustments for this and removed the rouge folder.  If the issue comes up again we can address it with a new issue, but the paths appear to have been corrected.

**Comment by PilotFish3447** [comment]
@ancaipen Confirming - those two images are now displaying in my Vision board repository.  All good.
